### ISSUE TITLE
pdf file gets misstake font unicode.

### ISSUE THREAD

**Issue by quocnho** [genack/gPOS#1]
Dear admins,
Thanks for your soft. I have download and use it. It's perfect for me. But I have 2 problems want to ask.
1. When I print invoice Asian font is mistake. (Font unicode charset utf8)
2. How can I edit ticket layout?
Thanks so much!

**Comment by cavaaden** [comment]
ok, we are solving the bug
1. When I print invoice Asian font is mistake. (Font unicode charset utf8)
   working on it.
2. How can I edit ticket layout?
3. Ticket, is not simple
   js / tpv.js line L11034
4. Invoices, delivery notes, is very simple with  fpdf
   modules / fpdf /

2014-12-19 1:56 GMT-05:00 quocnho notifications@github.com:

> Dear admins,
> Thanks for your soft. I have download and use it. It's perfect for me. But
> I have 2 problems want to ask.
> 1. When I print invoice Asian font is mistake. (Font unicode charset utf8)
> 2. How can I edit ticket layout?
> Thanks so much!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/genack/gPOS/issues/1.

## 

[  GNU ]
Libertad reto esencial del Hombre.
######################################
   » http://ayacsoft.net
   » cavaaden(en)gmail.com
#####################################

**Comment by quocnho** [comment]
Thanks for your support!
1. When I print Boleta the font mistake such as:
NGUYỄN QUỐC NHO --> Become: NGUY?N QU?C NHO 
May I print sale invoice like "Kadex" form?
2. When I "Presupuestos" after I Registrar Ticket->Recibir Ticket", it move to Recibir Pedios. I must change date reduce 1 day, it will display the ticket I register. Please check!
Thanks for your support!

**Comment by quocnho** [comment]
1. Can you use mpdf module instead of fpdf module?
2. We can keep fpdf module then we use: http://acko.net/blog/ufpdf-unicode-utf-8-extension-for-fpdf/
   Please help!
