### ISSUE TITLE
Install gPOS - XUL remote get error

### ISSUE THREAD

**Issue by quocnho** [genack/gPOS#3]
Dear admins,
Thanks for your soft and update,
1. When I install in to hosting, When login, it ask install gPOS - XUL, after I install success, it still ask again.

**Comment by cavaaden** [comment]
hi, check that "http or https"  your domain will use, in the link https://yourdomain/install/  >  view installation form:

> Configuración basica
> Dirección web de la aplicación : 
> [  https://yourdomain/       ]

**Comment by quocnho** [comment]
Everything is wright. Can you check for me? http://pos.fsofts.com/install/instalar.php

**Comment by cavaaden** [comment]
hi
http://pos.fsofts.com/xulentrar.php check

Warning:  ini_alter() has been disabled for security reasons in
/home/u845855777/public_html/pos/tool.php 4

change hosting provider :) or try to change php.ini settings

2016-01-02 12:56 GMT-05:00 Tony Nguyễn notifications@github.com:

> Everything is wright. Can you check for me?
> http://pos.fsofts.com/install/instalar.php
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/genack/gPOS/issues/3#issuecomment-168412417.

## 

[ Genack ]
   »
- genack.net http://genack.net   » cavaaden(en)gmail.com
  http://gmail.com      *
  » *gnu, libertad reto esencial del hombre. *
